on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create directory for extension
        run: |
          mkdir -p balamod_tools
          cp -r extension-src/* balamod_tools

      - uses: vimtor/action-zip@v1.2
        with:
          files: balamod_tools
          dest: balamod.aseprite-extension

      - uses: vimtor/action-zip@v1.2
        with:
          files: fonts
          dest: fonts.zip

      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_path: ./balamod.aseprite-extension
          asset_name: balamod.aseprite-extension
          asset_content_type: application/zip

      - name: Upload Release Fonts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_path: ./fonts.zip
          asset_name: fonts.zip
          asset_content_type: application/zip
